version: 1.2
    workflows:
        - subclass: CWL
          primaryDescriptorPath: /mynotebook.ipynb
          testParameterFiles: /mynotebook.ipynb
          readMePath: /mynotebook.ipynb
          authors:
              - name: Abdelilah Essiari
                email: aessiari@lbl.gov
