version: 1.2
    workflows:
        - subclass: CWL
          primaryDescriptorPath: <String>  # absolute path
          testParameterFiles: <String Array>  # absolute path
          readMePath: /mynotebook.ipynb
          authors:
              - name: Abdelilah Essiari
                email: aessiari@lbl.gov
